version: '3.4'
services:
  blebridge:
    build:
      context: .
    image: blebridge

    network_mode: host
    cap_add:
      - net_raw
      - net_admin

  mqtt:
    image: eclipse-mosquitto:1.4.12
    ports:
      - "1883:1883"    
